### ISSUE TITLE
Redefine snappy import path

### ISSUE THREAD

**Issue by 0x6e6562** [golang/snappy#12]
Until now we've been importing snappy using `code.google.com/p/snappy-go/snappy` but recently this has caused this issue:

```
package code.google.com/p/snappy-go/snappy: unable to detect version control system for code.google.com/ path
```

By changing the import to `github.com/golang/snappy/snappy`, we seem to have resolved the issue.

Is this the recommended way to reference this library?

**Comment by shurcooL** [comment]
The readme stays the import path is `github.com/google/go-snappy/snappy`, but when one goes to `github.com/google/go-snappy`, that redirects to this repo `github.com/golang/snappy`. Also, godoc.org works for https://godoc.org/github.com/golang/snappy/snappy but not https://godoc.org/github.com/google/go-snappy/snappy.

What is the actual import path of this Go package? If it's not the same as the repo path, it would be helpful to add an import path comment to resolve any doubts and ambiguities.

I just realized no one, aside from @gopherbot, is [watching](https://github.com/golang/snappy/watchers) this repo, so that's likely why this issue went unresolved for 7 days. /cc @nigeltao

**Comment by nigeltao** [comment]
Yes, the canonical path is now:
github.com/golang/snappy/snappy

Sorry that the github.com/google/go-snappy/snappy path is still around in some places. I was thinking of using gerrit with snappy, but in the end decided that it wasn't worth it. Apparently I've missed updating some of the stale links.

I'm also relatively new to the github workflow, so apologies for the late reply.

**Comment by shurcooL** [comment]
No problem, thank you for resolving this issue @nigeltao!
